# Generated by Django 4.2.4 on 2023-09-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/Internet.jpeg', null=True, upload_to=''),
        ),
    ]
