# Generated by Django 4.2.4 on 2023-11-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='commment',
            new_name='comment',
        ),
    ]
