# Generated by Django 4.2.4 on 2023-12-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_comment_review_commment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='commment',
            new_name='comment',
        ),
    ]
